### ISSUE TITLE
请添加 *.smartmailcloud.com 到 Proxy rules.

### ISSUE THREAD

**Issue by VincentSit** [BurpSuite/UPlus-Surge#1]
[Spark](https://sparkmailapp.com/) 是很多人常用的一款邮件应用，它的服务器 `app.smartmailcloud.com` 在国内很多地方是被墙掉的，所以麻烦加入到列表中，谢谢！

**Comment by VincentSit** [comment]
顺便，README 中的 IOS 应为 iOS。

**Comment by burpsuite** [comment]
好的,稍后我修改一下,暂时规则可能有点少,我之后会再把"gfwlist2pac"规则合并一下,然后重新整理下A-Z顺序需要一点时间.

**Comment by VincentSit** [comment]
不着急。

感谢你维护这份列表。
