### ISSUE TITLE
优酷6.2版本无法去广告

### ISSUE THREAD

**Issue by athlon128** [BurpSuite/UPlus-Surge#10]
优酷更新到最新版6.2之后，无法屏蔽广告了

**Comment by burpsuite** [comment]
已收到,尽快处理

**Comment by burpsuite** [comment]
优酷最新版本也是够恶心的了,把正常数据和广告数据一起发送,研究了一下午终于找到了规律,写了个PHP解析处理接口,重装并更新规则即可体验,CloudGate会接替优酷接口,替换掉里面的广告数据及秒针数据,我应该是第一个出针对优酷新版本拦截的吧,估计应该没有第二个,需要源代码请私信!

**Comment by burpsuite** [comment]
已修正!,如果还有问题请追问,如果没有问题的话,点击右下角"Close issue"谢谢!

**Comment by athlon128** [comment]
已经可以了，果然很强大！
