### ISSUE TITLE
内网规则建议

### ISSUE THREAD

**Issue by yehon** [BurpSuite/UPlus-Surge#11]
首先，感谢你维护这份规则表，这无疑给很多人带来了便利。
有个小建议，忘采纳：
说明：局域网 IP；
内容：IP-CIDR,100.64.0.0/10,DIRECT
备注：我司内网使用的是这个地址段…所以，如果直接使用你的规则，内网的内容全部不可访问，但在你的规则表中没有这个，所以，望添加，感谢。

**Comment by burpsuite** [comment]
好的,已添加,推荐通过README页面的在线方式导入,github里面不是最新的: ),同步需要一些时间.感谢提交

**Comment by yehon** [comment]
“https://async.be/Rule/Basic/Surge” 这个地址吗？
我是把这个文件下载下来以后，编辑的，因为我得填写自己的服务器地址和密码；
另外正好请教一个问题就是：
通过「云端规则」导入以后，每次更新，我的服务器地址和自动组都会被重置……这个怎么解决呢？查阅过你的规则说明，也没有找到解决办法。。

**Comment by yehon** [comment]
今天早上来公司，一直不能访问内网，搞了半天，终于定为问题：

`# IP-CIDR`

`IP-CIDR,10.0.0.0/8,DIRECT`

`IP-CIDR,127.0.0.0/8,DIRECT`

`IP-CIDR,172.16.0.0/12,DIRECT`

`IP-CIDR,192.168.0.0/16,DIRECT`

`IP-CIDR,100.64.0.0/10,DIRECT`

如上这几个`IP-CIDR`后面不能添加`,no-resolve`，否则，内网会不通………
请以后更新规则的时候，注意下这几个吧。。

**Comment by burpsuite** [comment]
云端规则已变更为高级规则New 使用JSON进行导入

**Comment by burpsuite** [comment]
好的

**Comment by yehon** [comment]
那个通过 Json 导入的，我一直没看懂怎么弄………………囧。

**Comment by burpsuite** [comment]
不过我感觉和IP-CIDR关系好像不大吧,所有的请求都在skip-proxy和bypass-tun之间就完成了.

**Comment by burpsuite** [comment]
高级规则New 页面有JSON导入模板,按需修改好后,将模板压缩,再进行Base64编码,然后可以保存为文件,或者直接粘贴在网址JSON=后面即可导入

**Comment by burpsuite** [comment]
高级规则New"JSON规则"里面的参数,同高级规则

**Comment by BurpSuite** [comment]
{
    "Configuration": {
        "Author": "BurpSuite",
        "Version": "1.0"
    },
    "Arguments": {
        "MITM": "true,15F5092B,https://raw.githubusercontent.com/BurpSuite/CloudGate-List/master/Rule/MITM",
        "External": "true,BurpSuite@0.0.0.0:6170",
        "MacOS": "true,1.2.3.4,5.6.7.8,3040,5030",
        "DNS": "true,8.8.8.8,8.8.4.4"
    },
    "General": {
        "EnhancedMode": "true",
        "Excludehost": "true",
        "WIFIAccess": "true",
        "Replica": "false",
        "USERAGENT": "true",
        "IPV6": "true",
        "Rule": "true"
    },
    "SERVER": [
        {
            "Number": "5"
        },
        {
            "SERVER1": "SERVER,custom,1.2.3.1,8081,aes-256-cfb,Password"
        }
    ],
    "ProxyGroup": [
        {
            "Number": "1"
        },
        {
            "Group1": "Proxy = select,SERVER",
        }
    ],
    "SUFFIX": {
        "USERAGENT": "Proxy",
        "KEYWORD": "Proxy",
        "IPCIDR": "Proxy",
        "Apple": "Proxy",
        "Other": "Proxy",
        "Proxy": "Proxy"
    },
    "CloudList": {
        "List": "https://raw.githubusercontent.com/BurpSuite/CloudGate-List/master/Rule/"
    }
}

**Comment by BurpSuite** [comment]
`{
    "Configuration": {
        "Author": "BurpSuite",
        "Version": "1.0"
    },
    "Arguments": {
        "MITM": "true,15F5092B,https://raw.githubusercontent.com/BurpSuite/CloudGate-List/master/Rule/MITM",
        "External": "true,BurpSuite@0.0.0.0:6170",
        "MacOS": "true,1.2.3.4,5.6.7.8,3040,5030",
        "DNS": "true,8.8.8.8,8.8.4.4"
    },
    "General": {
        "EnhancedMode": "true",
        "Excludehost": "true",
        "WIFIAccess": "true",
        "Replica": "false",
        "USERAGENT": "true",
        "IPV6": "true",
        "Rule": "true"
    },
    "SERVER": [
        {
            "Number": "5"
        },
        {
            "SERVER1": "SERVER,custom,1.2.3.1,8081,aes-256-cfb,Password"
        }
    ],
    "ProxyGroup": [
        {
            "Number": "1"
        },
        {
            "Group1": "Proxy = select,SERVER",
        }
    ],
    "SUFFIX": {
        "USERAGENT": "Proxy",
        "KEYWORD": "Proxy",
        "IPCIDR": "Proxy",
        "Apple": "Proxy",
        "Other": "Proxy",
        "Proxy": "Proxy"
    },
    "CloudList": {
        "List": "https://raw.githubusercontent.com/BurpSuite/CloudGate-List/master/Rule/"
    }
}`

**Comment by yehon** [comment]
IP-CIDR 关系很大，我是一个一个排除测试的，最终确认，我司内网用的是 `IP-CIDR,10.0.0.0/8`段，只要后面加上 `,no-resolve` 和注释掉该行，都会导致内网访问不了。
刚刚又测试了一遍…我也很奇怪，skip-proxy 和 bypass-tun 里面都包含了 `10.0.0.0/8`，但还是不行，必须要  `IP-CIDR,10.0.0.0/8`才可以……神了个奇。

**Comment by burpsuite** [comment]
好的,稍后我会进行修改.

**Comment by burpsuite** [comment]
好的,已临时修复,重新在线导入即可

**Comment by yehon** [comment]
再请教一下，刚才折腾了一下通过 Json 导入，用 `https://async.be/Rule/JSON/Surge?JSON= `+我的 Json 字符串，导入后，Surge 提示：错误，规则必须以 FINAL 结尾。

请问这个怎么办呢。。

**Comment by burpsuite** [comment]
应该是JSON格式错误,校验一下是否有错误,另外看看ProxyGroup or SERVER中有没有Emoji or 中文,如果有的话请将Emoji or 中文 转换成宽字节{unicode}

**Comment by yehon** [comment]
好的，我一会儿回电脑试试，我的服务器名称中的确有 Emoji ，但我的源码是用 编辑器 编辑的，已经是宽字符，但复制到你给的校验和转码网站就直接显示成 emoji 表情了，可能是这个原因？

发自我的 iPhone

**Comment by burpsuite** [comment]
是的,那个网站确实有点问题,转换后可能需要手动emoji为unicode替换一下,大概格式是这样
--------------------


{"Configuration":{"Author":"BurpSuite","Version":"1.0"},"Arguments":{"MITM":"true,15F5092B,https://raw.githubusercontent.com/BurpSuite/CloudGate-List/master/Rule/MITM","External":"false","MacOS":"false","DNS":"true,8.8.8.8,8.8.4.4"},"General":{"EnhancedMode":"true","Excludehost":"true","WIFIAccess":"false","Replica":"false","USERAGENT":"true","IPV6":"true","Rule":"true"},"SERVER":[{"Number":"1"},{"SERVER1":"\ud83e\udd17,custom,1.2.3.1,8081,aes-256-cfb,Password"}],"ProxyGroup":[{"Number":"1"},{"Group1":"\ud83e\udd14 = select,\ud83e\udd17"}],"SUFFIX":{"USERAGENT":"Proxy","KEYWORD":"Proxy","IPCIDR":"Proxy","Apple":"Proxy","Other":"Proxy","Proxy":"Proxy"},"CloudList":{"List":"https://raw.githubusercontent.com/BurpSuite/CloudGate-List/master/Rule/"}}



-----------------------------------------

https://async.be/Rule/JSON/Surge?JSON=eyJDb25maWd1cmF0aW9uIjp7IkF1dGhvciI6IkJ1cnBTdWl0ZSIsIlZlcnNpb24iOiIxLjAifSwiQXJndW1lbnRzIjp7Ik1JVE0iOiJ0cnVlLDE1RjUwOTJCLGh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9CdXJwU3VpdGUvQ2xvdWRHYXRlLUxpc3QvbWFzdGVyL1J1bGUvTUlUTSIsIkV4dGVybmFsIjoiZmFsc2UiLCJNYWNPUyI6ImZhbHNlIiwiRE5TIjoidHJ1ZSw4LjguOC44LDguOC40LjQifSwiR2VuZXJhbCI6eyJFbmhhbmNlZE1vZGUiOiJ0cnVlIiwiRXhjbHVkZWhvc3QiOiJ0cnVlIiwiV0lGSUFjY2VzcyI6ImZhbHNlIiwiUmVwbGljYSI6ImZhbHNlIiwiVVNFUkFHRU5UIjoidHJ1ZSIsIklQVjYiOiJ0cnVlIiwiUnVsZSI6InRydWUifSwiU0VSVkVSIjpbeyJOdW1iZXIiOiIxIn0seyJTRVJWRVIxIjoiXHVkODNlXHVkZDE3LGN1c3RvbSwxLjIuMy4xLDgwODEsYWVzLTI1Ni1jZmIsUGFzc3dvcmQifV0sIlByb3h5R3JvdXAiOlt7Ik51bWJlciI6IjEifSx7Ikdyb3VwMSI6Ilx1ZDgzZVx1ZGQxNCA9IHNlbGVjdCxcdWQ4M2VcdWRkMTcifV0sIlNVRkZJWCI6eyJVU0VSQUdFTlQiOiJQcm94eSIsIktFWVdPUkQiOiJQcm94eSIsIklQQ0lEUiI6IlByb3h5IiwiQXBwbGUiOiJQcm94eSIsIk90aGVyIjoiUHJveHkiLCJQcm94eSI6IlByb3h5In0sIkNsb3VkTGlzdCI6eyJMaXN0IjoiaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0J1cnBTdWl0ZS9DbG91ZEdhdGUtTGlzdC9tYXN0ZXIvUnVsZS8ifX0=

**Comment by yehon** [comment]
hello…我搞了半天，终于把 Emoji 的问题搞定了，但是，导入以后，提示：`Configuration Error Invalid line: `，而在其他的配置表中，我的服务器都是没问题的………………囧

**Comment by burpsuite** [comment]
是,这不是服务器问题,还是JSON问题,如果你导入上面规则要是没问题的话,那则不是规则的问题

**Comment by burpsuite** [comment]
你可以尝试做一些小的修改,比如改掉服务器再进行导入

**Comment by burpsuite** [comment]
又或者高级规则也不错 https://async.be/Rule/Advanced/Surge?&Group=1&SERVER1=ServerName,custom,127.0.0.1,80,aes-256-cfb,Password&DNS=true,2,8.8.8.8,8.8.4.4

**Comment by yehon** [comment]
吃饭去，晚上回家折腾一下……今天基本算旷工状态，哈哈哈哈哈，一天都在折腾这个 Json 导入。。。

**Comment by yehon** [comment]
高级规则不如 Json 支持的多吧？

发自我的 iPhone

**Comment by burpsuite** [comment]
是的,但是导入异常方便

**Comment by burpsuite** [comment]
不支持无限Group,无限服务器,无限DNS,还有几个功能

**Comment by yehon** [comment]
我会把 Json 导入吃透的，不然折腾了一半，岂不是白折腾了。

发自我的 iPhone

**Comment by burpsuite** [comment]
哈,一般人弄不到一半就放弃了,就说算了,不弄了哈哈

**Comment by burpsuite** [comment]
最简单的比如\ud83e\udd17,custom,1.2.3.1,8081,aes-256-cfb,Password 替换为你的,然后直接转换base64再导入就行了


------------------------
{"Configuration":{"Author":"BurpSuite","Version":"1.0"},"Arguments":{"MITM":"true,15F5092B,https://raw.githubusercontent.com/BurpSuite/CloudGate-List/master/Rule/MITM","External":"false","MacOS":"false","DNS":"true,8.8.8.8,8.8.4.4"},"General":{"EnhancedMode":"true","Excludehost":"true","WIFIAccess":"false","Replica":"false","USERAGENT":"true","IPV6":"true","Rule":"true"},"SERVER":[{"Number":"1"},{"SERVER1":"\ud83e\udd17,custom,1.2.3.1,8081,aes-256-cfb,Password"}],"ProxyGroup":[{"Number":"1"},{"Group1":"\ud83e\udd14 = select,\ud83e\udd17"}],"SUFFIX":{"USERAGENT":"Proxy","KEYWORD":"Proxy","IPCIDR":"Proxy","Apple":"Proxy","Other":"Proxy","Proxy":"Proxy"},"CloudList":{"List":"https://raw.githubusercontent.com/BurpSuite/CloudGate-List/master/Rule/"}}

**Comment by burpsuite** [comment]
不明白的问我,(今天)一般都在

**Comment by yehon** [comment]
好像只能从 iOS 端导入 URL，macOS 端不行？

**Comment by yehon** [comment]
搞定了，晚安。😊

**Comment by yehon** [comment]
还得再和你请教一个问题：
1. 这个 Json 的规则，和高级规则中的配置列表不一样？
2. Json 规则中有很多 Auto 的规则，而且和域名规则重复，比如 twitter，这个会导致，iOS 下访问没问题，但在 OS X 中出现无法访问的情况。

**Comment by burpsuite** [comment]
都是可以自行调整的,SUFFIX是后缀

**Comment by burpsuite** [comment]
JSON 2.0即将上线 demo:https://raw.githubusercontent.com/BurpSuite/TESTProject/master/New.json

**Comment by burpsuite** [comment]
SERVER是服务器列表 Group是代理组,代理组包含了服务器,Autoxy是代理组的名称,SUFFIX里包含的是代理组名称

**Comment by yehon** [comment]
好的，我试试。

**Comment by yehon** [comment]
我用 Json2.0 试了试，提示：`Invalid line: hostname=`;
我可以确定的是，我的 Json 没有配置错…………囧

**Comment by burpsuite** [comment]
json 2.0还没做出来呢😓，基本上完工了，明后天提交到正式环境上，修正了1.0众多bug.以及检测到json错误及时终止提示信息等，还有就是以前的json内容问题，比如不需要定义number，jsonobject 参数string->bool等

**Comment by burpsuite** [comment]
提交后我再通知你吧哈

**Comment by burpsuite** [comment]
已提交,可以导入了

**Comment by yehon** [comment]
已经搞定。^_^

**Comment by yehon** [comment]
还是会有那个问题：
`IP-CIDR,10.0.0.0/8,DIRECT,no-resolve` 中不可包含`,no-resolve`, 否则，我司内网会上不去…

提示内容：
> Error descriptions:  
> Socket closed by remote peer

**Comment by yehon** [comment]
另外，使用 Json 导入的规则，在 macOS 上访问 Google 等网站，会完全没有连接，在控制台中也看不到请求。但在 iOS 中却没事儿，如果是用 [https://async.be/Rule/Advanced/Surge/](url) 这个规则，则没问题；


chrome 提示：

> 无法访问此网站
> 
> www.google.com 的响应时间过长。
> 请试试以下办法：
> 检查网络连接
> 检查代理服务器和防火墙
> 运行网络诊断
> ERR_CONNECTION_TIMED_OUT

**Comment by burpsuite** [comment]
哦是这样的,如果删掉no-resolve,新版本的Surge会提示如下问题,多人反馈我,我才又加回去的.所以抱歉,还得自己修改一下哦.
![img_0460](https://cloud.githubusercontent.com/assets/14309190/24867948/42942ca0-1e41-11e7-8805-608347e0cd8e.PNG)

**Comment by burpsuite** [comment]
无论删除掉no-resolve,DIRECT,REJECT,Proxy都会提示这样的,另外顺序先后也调整了,也是会出现这样的提示,不知道你是否使用的是最新版本

**Comment by burpsuite** [comment]
JSON macOS查看一下SUFFIX是否包含存在正确的代理组

**Comment by yehon** [comment]
你截图中的的错误提示，我以前从未遇到过，直到第一次用你的规则时，我看没有 100 内网地址段，我就把他放到 Rule 上面了，那时候是第一次出现这个错误提示。
而我现在把 no-resolve 都去掉了，也没见这个提示…我是最新版，同时也是 TF 测试用户，有空我下个测试版看看？

**Comment by burpsuite** [comment]
好的,我知道可能是哪里的顺序出问题了,我处理下再回复你

**Comment by burpsuite** [comment]
已找到问题所在,正在处理中...

**Comment by burpsuite** [comment]
已修正

**Comment by yehon** [comment]
这。。。



发自我的 iPhone
