### ISSUE TITLE
高级规则New错误提示

### ISSUE THREAD

**Issue by wein00** [BurpSuite/UPlus-Surge#12]
服务器密码中，包含@、#等字符，或者密码长度超过13位均会出错：

显示如下：

a = custom,104.15.195,8080,chacha20,abcd,https://raw.githubusercontent.com/BurpSuite/CloudGate-List/master/Encrypt/Crypto@1234.com

望答复；

实例中不是真实 IP

**Comment by burpsuite** [comment]
已复现此问题,正在处理中...请稍后!

**Comment by burpsuite** [comment]
已修正

**Comment by wein00** [comment]
刚才已经尝试；
如存在多组服务器、且密码形式如上所述，问题依然存在；
如密码为：abcd@1234.com;   abce@123*org

望回复

**Comment by burpsuite** [comment]
可能是缓存问题,再重新导入一下就可以了
演示链接如下:
-----------------

https://async.be/Rule/JSON/Surge/?JSON=eyJDb25maWd1cmF0aW9uIjp7IkF1dGhvciI6IkJ1cnBTdWl0ZSIsIlZlcnNpb24iOiIyLjAifSwiQXJndW1lbnRzIjp7Ik1JVE0iOiJ0cnVlLDE1RjUwOTJCLGh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9CdXJwU3VpdGUvQ2xvdWRHYXRlLUxpc3QvbWFzdGVyL1J1bGUvTUlUTSIsIkV4dGVybmFsIjoidHJ1ZSxCdXJwU3VpdGVAMC4wLjAuMDo2MTcwIiwiTWFjT1MiOiJ0cnVlLDEuMi4zLjQsNS42LjcuOCwzMDQwLDUwMzAiLCJETlMiOiJ0cnVlLDguOC44LjgsOC44LjQuNCJ9LCJHZW5lcmFsIjp7IkVuaGFuY2VkTW9kZSI6dHJ1ZSwiRXhjbHVkZUhvc3QiOnRydWUsIldJRklBY2Nlc3MiOnRydWUsIlJlcGxpY2EiOmZhbHNlLCJVU0VSQUdFTlQiOnRydWUsIklQVjYiOmZhbHNlLCJSdWxlIjp0cnVlfSwiSW5mbyI6W3siU0VSVkVSIjp7IlNFUlZFUjEiOiJTRVJWRVJOYW1hLGN1c3RvbSwxLjIuMy4xLDgwODEsY2hhY2hhMjAsQOOAgSMxMjIxM0FDQkIhIiwiU0VSVkVSMiI6IlNFUlZFUk5hbWIsY3VzdG9tLDEuMi4zLjIsODA4MixjaGFjaGEyMCxA44CBIzEyMjEzQUNCQiEiLCJTRVJWRVIzIjoiU0VSVkVSTmFtYyxjdXN0b20sMS4yLjMuMyw4MDgzLGNoYWNoYTIwLEDjgIEjMTIyMTNBQ0JCISIsIlNFUlZFUjQiOiJTRVJWRVJOYW1kLGN1c3RvbSwxLjIuMy40LDgwODQsY2hhY2hhMjAsQOOAgSMxMjIxM0FDQkIhIiwiU0VSVkVSNSI6IlNFUlZFUk5hbWUsY3VzdG9tLDEuMi4zLjUsODA4NSxjaGFjaGEyMCxA44CBIzEyMjEzQUNCQiEifX0seyJHcm91cCI6eyJHcm91cDEiOiJQcm94eWEgPSBzZWxlY3QsU0VSVkVSTmFtYSxTRVJWRVJOYW1iLFNFUlZFUk5hbWMsU0VSVkVSTmFtZCxTRVJWRVJOYW1lIiwiR3JvdXAyIjoiUHJveHliID0gc2VsZWN0LFNFUlZFUk5hbWEsU0VSVkVSTmFtYixTRVJWRVJOYW1jLFNFUlZFUk5hbWQiLCJHcm91cDMiOiJQcm94eWMgPSBzZWxlY3QsU0VSVkVSTmFtYSxTRVJWRVJOYW1iLFNFUlZFUk5hbWUiLCJHcm91cDQiOiJQcm94eWQgPSBzZWxlY3QsU0VSVkVSTmFtZCxTRVJWRVJOYW1lIiwiR3JvdXA1IjoiQXV0b3h5ID0gdXJsLXRlc3QsU0VSVkVSTmFtYSwgU0VSVkVSTmFtYiwgdXJsID0gaHR0cDovL3d3dy5nc3RhdGljLmNvbS9nZW5lcmF0ZV8yMDQsIGludGVydmFsID0gNjAwLCB0b2xlcmFuY2UgPSAyMDAsIHRpbWVvdXQgPSA1In19XSwiU1VGRklYIjp7IkFwcGxlIjoiUHJveHlkIiwiUHJveHkiOiJBdXRveHkiLCJLRVlXT1JEIjoiUHJveHliIiwiSVBDSURSIjoiUHJveHljIiwiVVNFUkFHRU5UIjoiUHJveHlhIiwiT3RoZXIiOiJBdXRveHkifSwiT3RoZXIiOnsiQ3J5cHRvIjoiaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0J1cnBTdWl0ZS9DbG91ZEdhdGUtTGlzdC9tYXN0ZXIvRW5jcnlwdC9DcnlwdG8iLCJMaXN0IjoiaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0J1cnBTdWl0ZS9DbG91ZEdhdGUtTGlzdC9tYXN0ZXIvUnVsZS8ifX0=
