### ISSUE TITLE
反馈两个问题

### ISSUE THREAD

**Issue by LisonFan** [BurpSuite/UPlus-Surge#2]
1、优酷签到页面被误伤
2、阿里旅行客户端登录被误伤

**Comment by burpsuite** [comment]
好的，收到。我晚上看一下。

**Comment by burpsuite** [comment]
![img_0257](https://cloud.githubusercontent.com/assets/14309190/16451061/36e37206-3e33-11e6-8c74-0da6a46afec6.JPG)
![img_0250](https://cloud.githubusercontent.com/assets/14309190/16451067/42bb549a-3e33-11e6-86f1-cceaf38e19b3.PNG)
阿里旅行是没有问题的,我这个Proxy是我自己修改的,不过有一点是阿里旅行是走的GEOIP,我的规则默认的规则是GEOIP>CN.

**Comment by burpsuite** [comment]
优酷签到页面已修正,过两天再同步到Github,直接通过链接或AutoUPdate更新下就可以了呃...

**Comment by burpsuite** [comment]
如果还有什么问题可以继续追问哈,要是没有其他的问题请点击左下角的"Close And Comment"谢谢!
