### ISSUE TITLE
3656 行要删了，误删太多了

### ISSUE THREAD

**Issue by LisonFan** [BurpSuite/UPlus-Surge#4]
https://github.com/BurpSuite/UPlus-Surge/blob/master/Surge.Conf#L3656

**Comment by burpsuite** [comment]
好的,已经处理了,直接下载已经去掉了,Github下次更新时候一起同步.

**Comment by burpsuite** [comment]
如果还有问题的话,请继续追问,如果没有的话请点击右下角的"Close issue"谢谢!^ _ ^
