### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by silence0201** [BurpSuite/UPlus-Surge#7]
1.搜狐公共平台打不开
2.公司内网系统打不开

**Comment by burpsuite** [comment]
1.没有找到搜狐公共平台,如果有的话请附上网址,如果是搜狐公众平台的话是可以打开的.
2.公司内网比如?也请附上网址.内网格式有很多种,比如10.0.0.1之类,或者192.168.1.1或者172.0.0.1之类或者localhost等.另外请附上Request Log和TEST Rule.谢谢!

**Comment by silence0201** [comment]
1.搜获的问题可能是网络的问题,换了个网络就好啦
2.内网是10.x.x.x类型的,请求一直是失败,错误提示为Disconnect with reason: Testing rules failed: Testing rules failed due to a DNS error

**Comment by burpsuite** [comment]
看错误应该是DNS错误,这样,你删除掉DNS那一行,

**Comment by silence0201** [comment]
好啦 感谢作者

**Comment by alanhg** [comment]
> 好啦 感谢作者

Mac下如何删除单条DNS记录呢？

**Comment by alanhe421** [comment]
> 好啦 感谢作者

Mac下如何删除单条DNS记录呢？
